# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a21e717a7a34110344e9c79df00078026916c1334fe85ceaac562232008cb372620899545fdec2689abbe4b1ec2b66f58482e4cb120ee1298de0082e4299801

test:
  secret_key_base: 3375341148894a249c16d616bdf0af2d3c3241b8234afed67f16eff08528d2df3019de9c0199a98a016a6eaacd3f67077c8e2bf6201ae125658a70c6dbd081c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
